### thêm book
POST http://localhost:3000/book/
Content-Type: application/json

{
    "title": "Grand blue",
    "type": "Comic",
    "genres": [
        "comedy", "seinen", "school-life", "slice-of-life"
    ]
}

### cập nhật book
PATCH http://localhost:3000/book/sherlock-holme
Content-Type: application/json

{
    
}

### finish book
PATCH http://localhost:3000/book/finish/one-punch-man
Content-Type: application/json

{
    
}

### xoá book
DELETE http://localhost:3000/book/sherlock-holme

### lấy thông tin book
GET http://localhost:3000/book/one-piece
Content-Type: application/json

{
    "search": true
}

### Lấy danh sách book
GET http://localhost:3000/book/all