### thêm book
POST http://localhost:3000/book/
Content-Type: application/json

{
    "title": "One piece",
    "type": "Comic",
    "genres": [
        "comedy",
        "manga"
    ]
}

### cập nhật book
PATCH http://localhost:3000/book/sherlock-holme
Content-Type: application/json

{
    
}

### xoá book
DELETE http://localhost:3000/book/sherlock-holme

### lấy thông tin book
GET http://localhost:3000/book/one-punch-man

### Lấy danh sách book
GET http://localhost:3000/book/all/1