### thêm chapter
POST http://localhost:3000/chapter/
Content-Type: application/json

{
    "title": "Chapter 1",
    "book_endpoint": "one-piece",
    "images": ["aa","aaaaa"]
}

### cập nhật chapter
PATCH http://localhost:3000/chapter/one-shot
Content-Type: application/json

{
    "book_endpoint": "one-piece",
    "title": "Chapter 2"
}

### xoá chapter
DELETE http://localhost:3000/chapter/one-piece/chapter-2

### lấy thông tin chapter
GET http://localhost:3000/chapter/detail/giet-con-chim-nhai/chuong-1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoic2FpIiwiYXZhdGFyIjoiaHR0cHM6Ly90aHVtYnMuZHJlYW1zdGltZS5jb20vYi9kZWZhdWx0LWF2YXRhci1wcm9maWxlLWljb24tc29jaWFsLW1lZGlhLXVzZXItdmVjdG9yLWRlZmF1bHQtYXZhdGFyLXByb2ZpbGUtaWNvbi1zb2NpYWwtbWVkaWEtdXNlci12ZWN0b3ItcG9ydHJhaXQtMTc2MTk0ODc2LmpwZyIsImVtYWlsIjoiaW1hZ2VzYWl0YW1hQGdtYWlsLmNvbSIsInN0YXR1cyI6MCwicm9sZSI6MSwicGFzc3dvcmQiOiIifSwiaWF0IjoxNjQwOTc0ODg5LCJleHAiOjE2NzI1MTA4ODl9.9j6Ov8eys7a8m0S1G5LMDZw0_krjw6eNoOmANAC-m3U
Content-Type: application/json

{
    
}

### Lấy danh sách chapter
GET http://localhost:3000/chapter/all/giet-con-chim-nhai