### thêm chapter
POST http://localhost:3000/chapter/
Content-Type: application/json

{
    "title": "Chapter 2",
    "book_endpoint": "one-piece",
    "images": ["aa","aaaaa"]
}

### cập nhật chapter
PATCH http://localhost:3000/chapter/one-shot
Content-Type: application/json

{
    "book_endpoint": "one-piece",
    "title": "Chapter 2"
}

### xoá chapter
DELETE http://localhost:3000/chapter/one-piece/chapter-2

### lấy thông tin chapter
GET http://localhost:3000/chapter/one-piece/chapter-2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoic2FpIiwiYXZhdGFyIjoiaHR0cHM6Ly90aHVtYnMuZHJlYW1zdGltZS5jb20vYi9kZWZhdWx0LWF2YXRhci1wcm9maWxlLWljb24tc29jaWFsLW1lZGlhLXVzZXItdmVjdG9yLWRlZmF1bHQtYXZhdGFyLXByb2ZpbGUtaWNvbi1zb2NpYWwtbWVkaWEtdXNlci12ZWN0b3ItcG9ydHJhaXQtMTc2MTk0ODc2LmpwZyIsImVtYWlsIjoiaW1hZ2VzYWl0YW1hQGdtYWlsLmNvbSIsInN0YXR1cyI6MCwicm9sZSI6MSwicGFzc3dvcmQiOiIifSwiaWF0IjoxNjQwODA2NDE1LCJleHAiOjE2NDA4OTI4MTV9.rogPaE7LsML8Ub_qz8-E1ZOcigYcm7G2SDm222L5xlo

### Lấy danh sách chapter
GET http://localhost:3000/chapter/one-piece/all