### thêm genre
POST http://localhost:3000/genre/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoic2FpIiwiYXZhdGFyIjoiaHR0cHM6Ly90aHVtYnMuZHJlYW1zdGltZS5jb20vYi9kZWZhdWx0LWF2YXRhci1wcm9maWxlLWljb24tc29jaWFsLW1lZGlhLXVzZXItdmVjdG9yLWRlZmF1bHQtYXZhdGFyLXByb2ZpbGUtaWNvbi1zb2NpYWwtbWVkaWEtdXNlci12ZWN0b3ItcG9ydHJhaXQtMTc2MTk0ODc2LmpwZyIsImVtYWlsIjoiaW1hZ2VzYWl0YW1hQGdtYWlsLmNvbSIsInN0YXR1cyI6MCwicm9sZSI6MSwicGFzc3dvcmQiOiIifSwiaWF0IjoxNjQwOTc0ODg5LCJleHAiOjE2NzI1MTA4ODl9.9j6Ov8eys7a8m0S1G5LMDZw0_krjw6eNoOmANAC-m3U
Content-Type: application/json

{
    "title": "Văn học",
    "description": "Văn học"
}

### cập nhật genre
PATCH http://localhost:3000/genre/tieu-thuyet
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoic2FpIiwiYXZhdGFyIjoiaHR0cHM6Ly90aHVtYnMuZHJlYW1zdGltZS5jb20vYi9kZWZhdWx0LWF2YXRhci1wcm9maWxlLWljb24tc29jaWFsLW1lZGlhLXVzZXItdmVjdG9yLWRlZmF1bHQtYXZhdGFyLXByb2ZpbGUtaWNvbi1zb2NpYWwtbWVkaWEtdXNlci12ZWN0b3ItcG9ydHJhaXQtMTc2MTk0ODc2LmpwZyIsImVtYWlsIjoiaW1hZ2VzYWl0YW1hQGdtYWlsLmNvbSIsInN0YXR1cyI6MCwicm9sZSI6MSwicGFzc3dvcmQiOiIifSwiaWF0IjoxNjQwOTc0ODg5LCJleHAiOjE2NzI1MTA4ODl9.9j6Ov8eys7a8m0S1G5LMDZw0_krjw6eNoOmANAC-m3U
Content-Type: application/json

{
    "title": "Tiểu thuyết",
    "description": "Tiểu thuyết là một thể loại văn xuôi có hư cấu"
}

### xoá genre
DELETE http://localhost:3000/genre/tieu-thuyet

### lấy thông tin genre
GET http://localhost:3000/genre/detail/tu-truyen

### Lấy danh sách genre
GET http://localhost:3000/genre/all