### thêm report
POST http://localhost:3000/report/
Content-Type: application/json

{
    "endpoint": "a",
    "type": "A",
    "reason": "Don't known why"
}

### xoá report
DELETE http://localhost:3000/report/A/a

### xoá các report đã được xử lí
DELETE http://localhost:3000/report/read-report

### lấy thông tin report
GET http://localhost:3000/report/A/a

### Lấy danh sách report
GET http://localhost:3000/report/all